### ISSUE TITLE
定时设置

### ISSUE THREAD

**Issue by sunshine-yckx** [TomyJan/Yunzai-Kuro-Plugin#1]
大佬有空可以写一个json，使用户自定义各个任务的开始时间吗，谢谢

**Comment by TomyJan** [comment]
计划中的更新, 但是最近忙, 没时间, 得等到 9 月初才会继续更新

目前可以暂时自己手动修改 `/app/autoTask.js` 中的 cron

**Comment by sunshine-yckx** [comment]
okok，谢谢

**Comment by cj0928** [comment]
检查更新任务失败，好像是ghproxy被GFW淦碎了，新的是gh-proxy
