### ISSUE TITLE
请问能否增加一个允许私聊使用的功能

### ISSUE THREAD

**Issue by Lovelumine** [TomyJan/Yunzai-Kuro-Plugin#10]
请问能否增加一个
![c7d1742ec828ca7ec182b2f5e3607185](https://github.com/TomyJan/Yunzai-Kuro-Plugin/assets/105962147/b973f275-7461-4fee-ad32-d635fc95bd15)
允许私聊使用的功能，因为qq官方机器人开通私聊需要复杂的条件

**Comment by TomyJan** [comment]
你想把你的验证码往群里发？

**Comment by Lovelumine** [comment]
使用一次会失效吧，好像问题也不是很大

**Comment by Lovelumine** [comment]
我去，原来库洛验证码有效时间内可以重复使用

**Comment by TomyJan** [comment]
已支持在线登录~
