### ISSUE TITLE
签到推送好像不支持telegram

### ISSUE THREAD

**Issue by qwinwin** [TomyJan/Yunzai-Kuro-Plugin#11]
首先谢谢大佬的工作
我用的是 [TRSS-Yunzai](https://github.com/TimeRainStarSky/Yunzai)
tg bot可以正常发送信息并接收
签到功能正常 但是自动签到后的推送失败
log显示chatid错误 不知道该在哪里设置chatid

**Comment by TomyJan** [comment]
你是不是没设置botqq

**Comment by qwinwin** [comment]
> 你是不是没设置botqq

好像是  plugins/Yunzai-Kuro-Plugin/config/config.json中"botQQ": 0，这个该咋设置  直接该为tg用户id或者chatid？

**Comment by TomyJan** [comment]
@qwinwin 不知道，具体看你的适配器是怎么写的，这里实际上是 bot 账号的索引

**Comment by qwinwin** [comment]
> @qwinwin 不知道，具体看你的适配器是怎么写的，这里实际上是 bot 账号的索引

好的  我研究看看 谢谢
