### ISSUE TITLE
发送不了库洛帮助图片

### ISSUE THREAD

**Issue by hxwd94666** [TomyJan/Yunzai-Kuro-Plugin#12]
![~I15%Y3S QA3{IPQ59GQ0LN](https://github.com/TomyJan/Yunzai-Kuro-Plugin/assets/111326771/914a81ff-8139-4c34-936b-99def619926a)
如图，说是puppeteer Chromium 启动失败，但是我用喵喵帮助就能正常启动发图，不知道什么原因

**Comment by TomyJan** [comment]
@hxwd94666 其它生图功能有问题吗，插件日志调到debug看一下

**Comment by hxwd94666** [comment]
> @hxwd94666 其它生图功能有问题吗，插件日志调到debug看一下

其他功能，比如图鉴和攻略，是正常的。

**Comment by hxwd94666** [comment]
重启了下yunzai，帮助也可以正常发送了
