### ISSUE TITLE
0.3.4-rel版本，UI图渲染异常

### ISSUE THREAD

**Issue by OvertimeBunny** [TomyJan/Yunzai-Kuro-Plugin#15]
![Uploading b19dfdb1-c3fd-4989-b6f7-2173c5623bf5.png…]()

**Comment by TomyJan** [comment]
图呢?

**Comment by OvertimeBunny** [comment]
![](https://telegraph-image-buv.pages.dev/file/4649068f3bafc2fb7f6a4.png)

**Comment by TomyJan** [comment]
trss?

**Comment by OvertimeBunny** [comment]
> trss?

yes

**Comment by TomyJan** [comment]
trss问题

**Comment by OvertimeBunny** [comment]
有无解决方法

**Comment by OvertimeBunny** [comment]
在0.3.2版本中无UI异常的问题

**Comment by OvertimeBunny** [comment]
最新版本UI异常了

**Comment by TomyJan** [comment]
这边另一个有问题的群有解决方法是重做系统

**Comment by TomyJan** [comment]
抱歉, 询问这个问题的都是 trss 环境, 我也就认为是 trss 问题了, 刚把 bot 迁移到了 linux 才发现是在 linux 才有的问题, 目前已修复
