### ISSUE TITLE
关于在TrssYunzai上安装，生成图片出错的问题

### ISSUE THREAD

**Issue by XIAOKU2300** [TomyJan/Yunzai-Kuro-Plugin#17]
![4bdbe5b7aa18618f185ac43e4ae8c13a](https://github.com/user-attachments/assets/0c296e9d-d409-4a26-a7fb-3a4a95f3c214)

如图 

![d5e3d5299512f427aeda3cf0b6d37ce8](https://github.com/user-attachments/assets/3fd019d6-b1e7-47f9-834c-726303b687e6)

版本为最新版本

**Comment by TomyJan** [comment]
不支持trss

**Comment by TomyJan** [comment]
抱歉, 询问这个问题的都是 trss 环境, 我也就认为是 trss 问题了, 刚把 bot 迁移到了 linux 才发现是在 linux 才有的问题, 目前已修复

**Comment by TomyJan** [comment]
缘由我都解释清楚了，以及我好像并没有骂过你😅
