### ISSUE TITLE
能否加个查询体力

### ISSUE THREAD

**Issue by hbj2457** [TomyJan/Yunzai-Kuro-Plugin#7]
大佬可以给插件加个查询体力的功能吗，我自己是不知道有没有这方面的接口，希望大佬可以搞一个，比如`#鸣潮体力`就可以查询鸣潮体力恢复情况

**Comment by TomyJan** [comment]
回复怎么没发出去
已在 todo 中啊，现在优先在写抽卡

**Comment by TomyJan** [comment]
https://github.com/TomyJan/Yunzai-Kuro-Plugin/commit/81b4680e4ead89bb068318b125a24de9020383d4 , 体力推送晚点做
