### ISSUE TITLE
获取&分析 国际服的抽卡记录

### ISSUE THREAD

**Issue by wyf7685** [TomyJan/Yunzai-Kuro-Plugin#8]
参考了 [model/mcGachaData.js](https://github.com/TomyJan/Yunzai-Kuro-Plugin/blob/master/model/mcGachaData.js#L96) 的内容

对于国际服，可以用同样的方法从 `Client.log` 获取到形如 `https://aki-gm-resources-oversea.aki-game.net/aki/gacha/index.html#/record?svr_id=...` 的抽卡链接。

访问链接并监听请求，可以找到对 `https://gmserver-api.aki-game2.net/gacha/record/query` 的 POST 请求。

与国服获取数据流程相比，仅有请求域名存在差异。

| 链接 | 国服域名 | 国际服域名 |
| ---- | ---- | ---- |
| 抽卡记录页面 | `aki-gm-resources.aki-game.com` | `aki-gm-resources-oversea.aki-game.net` |
| POST 请求 | `gmserver-api.aki-game2.com` | `gmserver-api.aki-game2.net` |

![image](https://github.com/TomyJan/Yunzai-Kuro-Plugin/assets/69091901/f8e26f93-3228-473c-8610-cd7e0739a626)

**Comment by TomyJan** [comment]
感谢, 因为没有国际服的号所以一直没写
