### ISSUE TITLE
能否添加一个查看全部抽卡记录的功能

### ISSUE THREAD

**Issue by JadeVane** [TomyJan/Yunzai-Kuro-Plugin#9]
感谢作者开发这个插件，确实很好用。

想提个想法，能否像原神的抽卡界面一样，把所有池子的抽卡记录放在一张图里面，方便查看

**Comment by TomyJan** [comment]
想不出好方案, 所有卡池混一起, 还是一个接一个做同一张图?怎么做都觉得很别扭

**Comment by JadeVane** [comment]
大概做了个样式，可以看看效果怎样
![卡池demo](https://github.com/TomyJan/Yunzai-Kuro-Plugin/assets/34258753/301bb56b-7333-46d6-9ffd-b90c2712c29e)

**Comment by TomyJan** [comment]
直接全新做个吗, 也不是行

你这么会做, 要不直接交个pr上来吧

**Comment by JadeVane** [comment]
这个是设计软件画出来的，让我代码整一个还真不会...，js确实没学过

**Comment by TomyJan** [comment]
不行, 怎么设计都很难受, 以后再说吧
